### ISSUE TITLE
[BUG] Upload stays in PENDING status

### ISSUE THREAD

**Issue by kaloyan13** [unicef-drp/GeoRepo-OS#36]
**Describe the bug**
After uploading a geoJSON file to GeoRepo, its status stays PENDING.
In /flower I can see task layer_upload_preprocessing as SUCCESS.

**To Reproduce**
1. Create a new Dataset.
2. Click on 'Add data'.
3. Fill the fields in STEP 1.
4. Select file in STEP 2 and click Next.
5. Fields in STEP 3 are populated from file data. Select any of them, then click 'Save Level'.
6. Click on 'Import & Validate' in SUMMARY tab.
7. STEP 4 tab appears and Status is set to Started, spinning forever.

**Expected behavior**
Data gets uploaded.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22]
 - Browser [Firefox]
 - Version [116.0.3]

**Additional context**
I am using the master branch without docker.
All services (tile,validate,worker,beat,flower) are running, only change is in worker log:
```
[2023-08-21 13:59:37,300: INFO/MainProcess] Task layer_upload_preprocessing[cf5341cd-2a29-48d6-ae6b-c72eb26dcb54] received
[2023-08-21 13:59:37,301: INFO/ForkPoolWorker-4] layer_upload_preprocessing[cf5341cd-2a29-48d6-ae6b-c72eb26dcb54]: Running layer_upload_preprocessing for session 2
```

**Comment by gubuntu** [comment]
fixed by https://github.com/unicef-drp/GeoRepo/issues/1036 on Oct 2
